from enum import Enum


class ResponseSignal( str, Enum ):
    
    FILE_VALIDATED_SUCCESS ='FILE VALIDATED SUCCESS'.lower() 
    FILE_TYPE_NOT_SUPPORTED = 'FILE TYPE NOT SUPPORTED'.lower()
    FILE_SIZE_EXCEEDED = 'FILE SIZE EXCEEDED'.lower()
    FILE_UPLOAD_SUCCESS = 'FILE UPLOAD SUCCESS'.lower()
    FILE_UPLOAD_FAILED = 'FILE UPLOAD FAILED'.lower()
    PROCESSING_FAILED = 'PROCESSING FAILED'.lower()
    PROCESSING_SUCCESS = 'PROCESSING SUCCESS'.lower()
    NO_FILES_ERROR = 'NO FILES ERROR'.lower()
    PROJECT_NOT_FOUND = 'PROJECT NOT FOUND'.lower()
    INSERT_INTO_VECTOR_DB_ERROR = 'INSERT INTO VECTOR DB ERROR'.lower()
    INSERT_INTO_VECTOR_DB_SUCCESS = 'INSERT INTO VECTOR DB SUCCESS'.lower()
    VECTOR_DB_RETRIERVAL_SUCCESS = 'VECTOR DB RETRIERVAL SUCCESS'.lower()
    VECTOR_DB_SEARCH_ERROR = 'VECTOR DB SEARCH ERROR'.lower() 
    VECTOR_DB_SEARCH_SUCCESS = 'VECTOR DB SEARCH SUCCESS'.lower()
    RAG_ANSWER_ERROR = 'FAILED RETRIEVING AUGMENTED ANSWERS'.lower()
    RAG_ANSWER_sUCCESS = 'RETRIEVING AUGMENTED ANSWERS SUCCESS'.lower()